version: "3"
services:
    
    client:
        build:
            context: ./client
        depends_on:
            - api
        restart: on-failure
        env_file: .env

    proxy_server:
        image: nginx:1.17
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 4000:80
        depends_on:
            - client

